version: "3.9"
services:
  db:
    image: postgres:13.3
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=mydb
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
  liquibase:
    build:
      context: .
      dockerfile: Dockerfile
    image: liquibase:4.21.1
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/mydb
      - JDBC_USERNAME=user
      - JDBC_PASSWORD=password
      - JDBC_DRIVER=org.postgresql.Driver
    container_name: liquibase
    depends_on:
      - db
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://db:5432/mydb
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DRIVER=org.postgresql.Driver
    container_name: myapp
    depends_on:
      - db
      - liquibase
