version: "3.9"

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
      - dataSource.user=user
      - dataSource.password=password
      - dataSource.databaseName=mydb